### PR TITLE
Update Arabic Translation

### PR DESCRIPTION
**Pull request by motazsaad**

### CODE REVIEW

**Comment by faf** [comment]
@motazsaad Thanks for your contribution. I'll check and merge it in the near future.

**Comment by faf** [comment]
@motazsaad I've checked the translation. Thank you for your work, it's really impressive. However, there is a number of tiny issues that have to be solved before update the translation.

1. Mibew Messenger as well as Apache Software License should not be translated. So, could you please fix the constants listed below?

[msgid "About Mibew Messenger"](https://github.com/Mibew/i18n/blob/615eaba1703aff709618e69981945b85b24d3207/translations/ar/translation.po#L63)
[msgid "Mibew Messenger is an open-source live support application licensed under the terms of the Apache License 2.0."](https://github.com/Mibew/i18n/blob/615eaba1703aff709618e69981945b85b24d3207/translations/ar/translation.po#L643)
[msgid "PHP version is {0}, but Mibew Messenger works with {1} and later versions."](https://github.com/Mibew/i18n/blob/615eaba1703aff709618e69981945b85b24d3207/translations/ar/translation.po#L753)

2. Are you sure about constants listed below? Don't get me wrong, I don't speak Arabic, but Google Translate makes me doubt.

[msgid "Cannot store database structure version. Error {0}"](https://github.com/Mibew/i18n/blob/615eaba1703aff709618e69981945b85b24d3207/translations/ar/translation.po#L181) - it's about storing the version (i.e. a number) of the database structure, not about storing its copy.

These ones are about uploading, not downloading:

- [msgid "Choose the translation file to upload."](https://github.com/Mibew/i18n/blob/615eaba1703aff709618e69981945b85b24d3207/translations/ar/translation.po#L249)
- [msgid "On this page you can upload a custom translation file."](https://github.com/Mibew/i18n/blob/615eaba1703aff709618e69981945b85b24d3207/translations/ar/translation.po#L711)
- [msgid "Upload translation"](https://github.com/Mibew/i18n/blob/615eaba1703aff709618e69981945b85b24d3207/translations/ar/translation.po#L1085)

[msgid "Updated to {0}"](https://github.com/Mibew/i18n/blob/615eaba1703aff709618e69981945b85b24d3207/translations/ar/translation.po#L1077) - it's not about upload, it's about update (particularly, of the database structure).

[msgid "System will check updates for the core and plugins automatically using cron"](https://github.com/Mibew/i18n/blob/615eaba1703aff709618e69981945b85b24d3207/translations/ar/translation.po#L967) - it's about all updates both for Mibew Messenger itself and for installed official plugins.

[msgid "Time locale"](https://github.com/Mibew/i18n/blob/615eaba1703aff709618e69981945b85b24d3207/translations/ar/translation.po#L1033) - it's about locale of time (i.e. about translation of days, months, etc.), not about local time.

[msgid "Your name"](https://github.com/Mibew/i18n/blob/615eaba1703aff709618e69981945b85b24d3207/translations/ar/translation.po#L1227) - are you sure that your translation is more correct than existing one?

[msgid "Start Chat"](https://github.com/Mibew/i18n/blob/615eaba1703aff709618e69981945b85b24d3207/translations/ar/translation.po#L945) - are you sure that this constant should be translated in such detailed way?

[msgid "Operator canceled invitation"](https://github.com/Mibew/i18n/blob/615eaba1703aff709618e69981945b85b24d3207/translations/ar/translation.po#L719) - are you sure that this translation is correct?


At the moment I've created a dedicated branch based upon your commit that will be merged with the master once everything will be clarified. Once again thank for your work. :+1:

**Comment by faf** [comment]
So I've merged into the master branch all constants except for those mentioned above. Feel free to contact me about them anytime.

**Comment by motazsaad** [comment]
Thanks so much for merging, and It is OK for the unresolved points.

**Pull request merged**
