### PR TITLE
Update mail_templates.yml

### PR DESCRIPTION
**Pull request by Jonadabe**

### CODE REVIEW

**Comment by faf** [comment]
@Jonadabe Hi! Thanks for your contribution! :)

Could you please shed some light on this PR? As far as I understand original phrases "This will let you choose another password" and "You have a message" are more literally translated by the existing translation. Am I wrong and there are some language nuances and/or stable expressions in Portugese?

**Comment by faf** [comment]
@Jonadabe ping

**Comment by Jonadabe** [comment]
@faf  I proposed corrections to errors in portuguese language. They aren't nuances.

**Comment by faf** [comment]
Well, ok then. :)

**Pull request merged**
